export const FORM_DATA = [
    {
        forItem: "validationDefault01",
        labelClass: "form-label",
        label: "First Name *",
        type: "text",
        placeholder: "Enter your First Name",
        inputClass: "form-control",
        id: 0,
        isRequired: true,
    },
    {
        forItem: "validationDefault02",
        labelClass: "form-label",
        label: "Last Name *",
        type: "text",
        placeholder: "Enter your First Name",
        inputClass: "form-control",
        id: 1,
        isRequired: true,
    },
    {
        forItem: "validationDefault03",
        labelClass: "form-label",
        label: "Company *",
        type: "text",
        placeholder: "Enter your First Name",
        inputClass: "form-control",
        id: 2,
        isRequired: true,
    },
    {
        forItem: "validationDefaultUsername",
        labelClass: "form-label",
        label: "Email *",
        type: "email",
        placeholder: "Enter your Email",
        inputClass: "form-control",
        id: 3,
        isRequired: true,
    },
    {
        forItem: "validationDefault04",
        labelClass: "form-label",
        label: "Job Title *",
        type: "text",
        placeholder: "Enter your Job title",
        inputClass: "form-control",
        id: 4,
        isRequired: true,
    },
    {
        forItem: "validationDefault05",
        labelClass: "form-label",
        label: "Country",
        type: "text",
        placeholder: "Enter your Country",
        inputClass: "form-control",
        id: 5,
        isRequired: false,
    },
    {
        forItem: "validationDefault06",
        labelClass: "form-label",
        label: "State *",
        type: "text",
        placeholder: "Enter your State",
        inputClass: "form-control",
        id: 6,
        isRequired: true,
    },
    {
        forItem: "validationDefault07",
        labelClass: "form-label",
        label: "Zip code *",
        type: "text",
        placeholder: "Enter your Zip code",
        inputClass: "form-control",
        id: 7,
        isRequired: true,
    }
]