export const INPUT_DATA = [
    {
        id: 0,
        controlId: "firstName",
        type: "text",
        label: "First Name*",
        required: true,
        placeholder: "Enter Your First Name",
    },
    {
        id: 1,
        controlId: "lastName",
        type: "text",
        label: "Last Name*",
        required: true,
        placeholder: "Enter Your Last Name",
    },
    {
        id: 2,
        controlId: "company",
        type: "text",
        label: "Company*",
        required: true,
        placeholder: "Enter Your Company",
    },
    {
        id: 3,
        controlId: "email",
        type: "email",
        label: "Email*",
        required: true,
        placeholder: "Enter Your Email",
    },
    {
        id: 4,
        controlId: "jobTitle",
        type: "text",
        label: "Job Title*",
        required: true,
        placeholder: "Enter Job Title",
    },
    {
        id: 5,
        controlId: "country",
        type: "text",
        label: "Country",
        required: false,
        placeholder: "Enter Your Country",
    },
    {
        id: 6,
        controlId: "state",
        type: "text",
        label: "State*",
        required: true,
        placeholder: "Enter Your State",
    },
    {
        id: 7,
        controlId: "zipCode",
        type: "text",
        label: "Zip code*",
        required: true,
        placeholder: "Enter Your Zip Code",
    },
]